### ISSUE TITLE
how can i use slicerFX in this scene

### ISSUE THREAD

**Issue by buzzhoot** [keijiro/KvantLattice#1]
it it possible to use slicerFx in this scene?

**Comment by keijiro** [comment]
Unfortunately, it can't. You have to customize the surface shader (Kvant/Lattice/Surface) to add such an effect.

I added a simple slicing effect to the shader in VJ05 project.

https://github.com/keijiro/VJ05/blob/master/Assets/Kvant/Lattice/Shaders/Surface.shader#L96
